spring.datasource.url=jdbc:postgresql://localhost:5432/bd_urbanride
spring.datasource.username=postgres
spring.datasource.password=urban2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080