server.port=8080

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_terminal
spring.datasource.username=postgres
spring.datasource.password=lafiru123
spring.datasource.driver-class-name=org.postgresql.Driver

# Desactivar que Hibernate modifique tus tablas (usa tus tablas de xxdd.txt tal cual están)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true